import { requestJson } from './http.js'
import type { HttpTransport } from './http.js'

export type OAuthProviderId = 'salesforce' | 'hubspot' | 'slack' | 'teams' | 'fathom'

export interface OAuthAuthorizationInput {
  clientId: string
  redirectUri: string
  state: string
  scopes?: string[]
  tenant?: string
  loginUrl?: string
}

export interface OAuthExchangeInput extends OAuthAuthorizationInput {
  clientSecret: string
  code: string
}

const defaults: Record<OAuthProviderId, { authorize: string; token: string; scopes: string[] }> = {
  salesforce: {
    authorize: 'https://login.salesforce.com/services/oauth2/authorize',
    token: 'https://login.salesforce.com/services/oauth2/token',
    scopes: ['api', 'refresh_token'],
  },
  hubspot: {
    authorize: 'https://app.hubspot.com/oauth/authorize',
    token: 'https://api.hubapi.com/oauth/2026-03/token',
    scopes: [
      'crm.objects.companies.read', 'crm.objects.companies.write',
      'crm.objects.contacts.read', 'crm.objects.contacts.write',
      'crm.objects.deals.read', 'crm.objects.deals.write',
      'crm.objects.owners.read',
    ],
  },
  slack: {
    authorize: 'https://slack.com/oauth/v2/authorize',
    token: 'https://slack.com/api/oauth.v2.access',
    scopes: ['chat:write'],
  },
  teams: {
    authorize: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
    token: 'https://login.microsoftonline.com/common/oauth2/v2.0/token',
    scopes: ['offline_access', 'User.Read', 'ChannelMessage.Send'],
  },
  fathom: {
    authorize: '',
    token: 'https://api.fathom.ai/external/v1/oauth2/token',
    scopes: ['public_api'],
  },
}

/** Builds a state-bearing authorization URL. State generation/verification belongs to the portal. */
export function oauthAuthorizationUrl(provider: OAuthProviderId, input: OAuthAuthorizationInput): string {
  const config = endpoints(provider, input)
  if (!config.authorize) throw new Error('Fathom authorization URLs must be generated by its registered-app SDK')
  const url = new URL(config.authorize)
  url.searchParams.set('client_id', required(input.clientId, 'clientId'))
  url.searchParams.set('redirect_uri', required(input.redirectUri, 'redirectUri'))
  url.searchParams.set('state', required(input.state, 'state'))
  url.searchParams.set('response_type', 'code')
  const scopes = input.scopes ?? config.scopes
  url.searchParams.set('scope', provider === 'slack' ? scopes.join(',') : scopes.join(' '))
  if (provider === 'teams') url.searchParams.set('response_mode', 'query')
  return url.toString()
}

/** Exchanges a verified callback code; secrets are form-encoded in the body, never the URL. */
export async function exchangeOAuthCode(
  provider: OAuthProviderId,
  input: OAuthExchangeInput,
  http: HttpTransport,
): Promise<Record<string, string>> {
  const config = endpoints(provider, input)
  const form = new URLSearchParams({
    grant_type: 'authorization_code', code: required(input.code, 'code'),
    client_id: required(input.clientId, 'clientId'), client_secret: required(input.clientSecret, 'clientSecret'),
    redirect_uri: required(input.redirectUri, 'redirectUri'),
  })
  const value = await requestJson<Record<string, unknown>>(http, {
    method: 'POST', url: config.token,
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: form.toString(),
  })
  if (provider === 'slack' && value.ok !== true) throw new Error('Slack OAuth exchange failed')
  const accessToken = stringValue(value.access_token, 'OAuth response access_token')
  return {
    accessToken,
    ...(typeof value.refresh_token === 'string' && value.refresh_token ? { refreshToken: value.refresh_token } : {}),
    ...(provider === 'salesforce' && typeof value.instance_url === 'string' ? { instanceUrl: value.instance_url } : {}),
    clientId: input.clientId,
    clientSecret: input.clientSecret,
    ...(input.tenant ? { tenant: input.tenant } : {}),
  }
}

export async function refreshOAuthToken(
  provider: OAuthProviderId,
  credentials: Record<string, string>,
  http: HttpTransport,
): Promise<Record<string, string>> {
  const clientId = required(credentials.clientId ?? '', 'clientId')
  const clientSecret = required(credentials.clientSecret ?? '', 'clientSecret')
  const refreshToken = required(credentials.refreshToken ?? '', 'refreshToken')
  const input: OAuthAuthorizationInput = {
    clientId, redirectUri: credentials.redirectUri ?? 'https://localhost.invalid', state: 'refresh',
    ...(credentials.tenant ? { tenant: credentials.tenant } : {}),
    ...(credentials.loginUrl ? { loginUrl: credentials.loginUrl } : {}),
  }
  const config = endpoints(provider, input)
  const form = new URLSearchParams({ grant_type: 'refresh_token', refresh_token: refreshToken, client_id: clientId, client_secret: clientSecret })
  const value = await requestJson<Record<string, unknown>>(http, {
    method: 'POST', url: config.token,
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' }, body: form.toString(),
  })
  if (provider === 'slack' && value.ok !== true) throw new Error('Slack OAuth refresh failed')
  return {
    ...credentials,
    accessToken: stringValue(value.access_token, 'OAuth response access_token'),
    refreshToken: typeof value.refresh_token === 'string' && value.refresh_token ? value.refresh_token : refreshToken,
    ...(provider === 'salesforce' && typeof value.instance_url === 'string' ? { instanceUrl: value.instance_url } : {}),
  }
}

function endpoints(provider: OAuthProviderId, input: OAuthAuthorizationInput) {
  const config = defaults[provider]
  if (provider === 'salesforce' && input.loginUrl) {
    const login = new URL(input.loginUrl)
    if (login.protocol !== 'https:' || (login.hostname !== 'salesforce.com' && !login.hostname.endsWith('.salesforce.com'))) {
      throw new Error('Salesforce loginUrl must be an HTTPS endpoint on salesforce.com')
    }
    const base = login.origin
    return { ...config, authorize: `${base}/services/oauth2/authorize`, token: `${base}/services/oauth2/token` }
  }
  if (provider === 'teams' && input.tenant) {
    const tenant = encodeURIComponent(input.tenant)
    return { ...config, authorize: `https://login.microsoftonline.com/${tenant}/oauth2/v2.0/authorize`, token: `https://login.microsoftonline.com/${tenant}/oauth2/v2.0/token` }
  }
  if (provider === 'fathom' && input.loginUrl) {
    const authorize = new URL(input.loginUrl)
    if (authorize.protocol !== 'https:' || (authorize.hostname !== 'fathom.video' && !authorize.hostname.endsWith('.fathom.video'))) {
      throw new Error('Fathom authorization URL must be an HTTPS endpoint on fathom.video')
    }
    return { ...config, authorize: authorize.toString() }
  }
  return config
}

function required(value: string, name: string): string {
  if (!value.trim()) throw new Error(`${name} is required`)
  return value
}

function stringValue(value: unknown, name: string): string {
  if (typeof value !== 'string' || !value) throw new Error(`${name} is required`)
  return value
}
